### ISSUE TITLE
Random error Error: connect ETIMEDOUT 107.178.243.76:80

### ISSUE THREAD

**Issue by cashbit** [sphero-inc/sphero-sdk-raspberrypi-nodejs#1]
This error occurs after a node dist/server.js, testing some api-docs as reported below

```
info: DRIVE (0X16) >> Response -- Route: /drive/rawMotors/2 | Method: PUT
debug: DRIVE (0X16) >> Response -- Route: /drive/rawMotors/2 | Method: PUT | Device: Drive (0x16) (22) | Command: RawMotors (1) | SourceId: 1 | TargetId: 18 | Payload: 
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 107.178.243.76:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by CyborgEric** [comment]
Have you made any progress with your issue?  I just tried the endpoint on my end and it worked via Swagger.  What values are you using for the body?

**Comment by cashbit** [comment]
Hi, i think solved the problem.

It’s not so clear which Id is needed so using the wrong id you receive the error message (bad command).

If I can I suggest to clarify the different ids needed.

Best regards
Carlo
Il 26 dic 2019, 04:13 +0100, Eric Reed <notifications@github.com>, ha scritto:

**Comment by CyborgEric** [comment]
Glad you got it solved!
